#!/usr/bin/zsh

# Set log file name
log_file_name="fzf.log"

#############################################################################################################################
## FZF Configuration
#############################################################################################################################

# Default FZF commands
export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix"
export FZF_ALT_C_COMMAND="bfs -color -mindepth 1 -exclude \( -name .git \) -type d -printf '%P\n' 2>/dev/null"
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"
export FZF_CTRL_T_COMMAND="bfs -color -mindepth 1 -exclude \( -name .git \) -printf '%P\n' 2>/dev/null"

export FZF_DEFAULT_OPTS='
--ansi
--bind "ctrl-/:toggle-preview"
--bind "ctrl-y:execute-silent(printf {} | cut -f 2- | pbcopy)"
--border
'"$FZF_COLORS"'
--info=inline
--preview "~/scripts/fzf_preview {}"
--preview-window right,60%
-i
'

# FZF options for CTRL-R
export FZF_CTRL_R_OPTS="
--preview 'echo {}' --preview-window up:3:hidden:wrap
--bind 'ctrl-/:toggle-preview'
--bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
--color header:italic
--header 'Press CTRL-Y to copy command into clipboard'"

#############################################################################################################################
## FZF Functions
#############################################################################################################################

# FZF Completion Run with Custom Preview
function _fzf_comprun() {
  local command="$1"
  shift
  case "$command" in
  cd)
    mylog "Running FZF with directory preview using tree for command: cd" "$log_file_name"
    fzf "$@" --preview 'tree -C {} | head -200'
    ;;
  *)
    mylog "Running FZF with custom preview script for command: $command" "$log_file_name"
    fzf "$@" --preview '~/.local/bin/lessfilter {}'
    ;;
  esac
}

# Custom FZF Git Integration
function _fzf_git_fzf() {
  mylog "Running FZF Git Integration" "$log_file_name"
  fzf-tmux \
    --ansi \
    --bind 'ctrl-/:toggle-preview' \
    --bind 'ctrl-y:execute-silent(printf {} | cut -f 2- | pbcopy)' \
    --bind='ctrl-/:change-preview-window(down,50%,border-top|hidden|)' \
    $FZF_COLORS --color=dark \
    --height '95%' \
    --info=inline \
    -l "90%" \
    --layout=reverse --multi --height=90% --min-height=30 \
    --preview '~/.local/bin/lessfilter {}' \
    --preview-window 'right,75%' \
    -i \
    -p90%,90% \
    "$@"
}

# Update FZF from Source
function fzf-update() {
  mylog "Updating FZF from source" "$log_file_name"
  local dir
  dir="$(pwd)"
  cd ~/.fzf && git pull && ./install --no-bash --no-zsh --no-fish --no-key-bindings --no-completion --no-update-rc
  cd "$dir"
  exec $SHELL -l
}

#############################################################################################################################
## FZF Completion
#############################################################################################################################

export FZF_COMPLETION_TRIGGER=''
bindkey "^I" expand-or-complete
bindkey "^[[Z" expand-or-complete
bindkey '^ ' fzf-completion
bindkey '^I' $fzf_default_completion

# FZF Path Completion Generator
function _fzf_compgen_path() {
  mylog "Generating FZF path completion" "$log_file_name"
  bfs -H "$1" -color -exclude \( -name .git \) 2>/dev/null
}

# FZF Directory Completion Generator
function _fzf_compgen_dir() {
  mylog "Generating FZF directory completion" "$log_file_name"
  bfs -H "$1" -color -exclude \( -name .git \) -type d 2>/dev/null
}
