#!/usr/bin/zsh

# Set log file name
log_file_name="git.log"

#############################################################################################################################
## Git Functions
#############################################################################################################################

# Load Git version for compatibility checks
autoload -Uz is-at-least
git_version=$(git version 2>/dev/null | awk '{print $3}')

# Get the current branch name
function current_branch() {
  local branch_name
  branch_name=$(git_current_branch)
  mylog "Current branch: $branch_name" "$log_file_name"
  echo "$branch_name"
}

# Display Git log with a specific format
function _git_log_prettily() {
  if [ -n "$1" ]; then
    git log --pretty="$1"
    mylog "Displayed git log with format: $1" "$log_file_name"
  fi
}

# Display a message if work in progress (WIP) commits are present
function work_in_progress() {
  if command git -c log.showSignature=false log -n 1 2>/dev/null | grep -q -- "--wip--"; then
    mylog "Work in progress detected" "$log_file_name"
    echo "WIP!!"
  fi
}

# Determine the main branch (main, master, etc.)
function git_main_branch() {
  command git rev-parse --git-dir &>/dev/null || return
  local ref
  for ref in refs/{heads,remotes/{origin,upstream}}/{main,trunk,mainline,default}; do
    if command git show-ref -q --verify "$ref"; then
      mylog "Main branch detected: ${ref:t}" "$log_file_name"
      echo "${ref:t}"
      return
    fi
  done
  mylog "Defaulting to 'master' branch" "$log_file_name"
  echo "master"
}

# Determine the development branch (develop, dev, etc.)
function git_develop_branch() {
  command git rev-parse --git-dir &>/dev/null || return
  local branch
  for branch in dev devel development; do
    if command git show-ref -q --verify refs/heads/$branch; then
      mylog "Development branch detected: $branch" "$log_file_name"
      echo "$branch"
      return
    fi
  done
  mylog "Defaulting to 'develop' branch" "$log_file_name"
  echo develop
}

unset git_version

#############################################################################################################################
## Git Aliases
#############################################################################################################################

alias gitree='git log --oneline --graph --decorate --all'

#############################################################################################################################
## Git Utility Functions
#############################################################################################################################

# Checkout a branch using fzf
function gco() {
  local branch
  branch=$(_fzf_git_each_ref --no-multi | xargs git checkout)
  mylog "Checked out branch: $branch" "$log_file_name"
}

# Clone a GitHub repository using SSH
function clone() {
  git clone "git@github.com:$1"
  mylog "Cloned repository: git@github.com:$1" "$log_file_name"
}

# Create a WIP commit
function wip() {
  git add -A .
  local now
  now=$(date +"%Y-%m-%dT%H:%M:%S TZ%Z(%a, %j)")
  git commit --no-verify -S -m "wip: checkpoint at $now"
  git push
  mylog "Created WIP commit at $now" "$log_file_name"
}

# Create a signed commit with an optional message
function commit() {
  if [[ -z "$1" ]]; then
    git commit -S
    mylog "Created a signed commit without a message" "$log_file_name"
  else
    git commit -S -m "$1"
    mylog "Created a signed commit with message: $1" "$log_file_name"
  fi
}

# Get the last commit message with timestamp
function lastcommit() {
  local message
  message=$(git log --pretty='format:%s 🕑 %cr' 'HEAD^..HEAD' | head -n 1)
  mylog "Last commit message: $message" "$log_file_name"
  echo "$message"
}

#############################################################################################################################
## GitHub Functions
#############################################################################################################################

# Create a GitHub pull request
function createpr() {
  local branch_target
  branch_target=$(test -z "$1" && echo "$(getBranchFzf)" || echo "$1")
  gh pr create --base "$branch_target" -a "@me" "${@:2}"
  mylog "Created GitHub PR based on branch: $branch_target" "$log_file_name"
}

# Alias for creating a pull request
function newpr() {
  createpr "$1"
}

# Create a draft GitHub pull request
function draft() {
  createpr "$1" "--draft"
  mylog "Created draft GitHub PR based on branch: $1" "$log_file_name"
}
