#!/usr/bin/zsh

zellij_tab_name_update() {
  if [[ -z $ZELLIJ ]]; then
    return
  fi

  local tab_name=''
  local current_tab=''
  local tab_count=0

  while IFS= read -r line; do
    ((tab_count++))
    if [[ $line == "(current)" ]]; then
      current_tab=$tab_count
    fi
  done < <(zellij action query-tab-names)

  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    tab_name+=$(basename "$(git rev-parse --show-toplevel)")/
    tab_name+=$(git rev-parse --show-prefix)
    tab_name=${tab_name%/}
  else
    tab_name=$PWD
    if [[ $tab_name == $HOME ]]; then
      tab_name="~"
    else
      tab_name=${tab_name##*/}
    fi
  fi

  zellij action rename-tab "$current_tab $tab_name"
}
